import type { RouteRecordRaw } from 'vue-router'

export const toolRoutes: RouteRecordRaw[] = [
  {
    path: 'toolbox/picker',
    name: 'tool-picker',
    component: () => import('../views/tools/RandomPicker.vue'),
    meta: { title: '随机点名', icon: '🎯' },
  },
  {
    path: 'toolbox/timer',
    name: 'tool-timer',
    component: () => import('../views/tools/Timer.vue'),
    meta: { title: '倒计时', icon: '⏱️' },
  },
  {
    path: 'toolbox/calc',
    name: 'tool-calc',
    component: () => import('../views/tools/Calc.vue'),
    meta: { title: '课堂计算器', icon: '🧮' },
  },
  {
    path: 'toolbox/comment',
    name: 'tool-comment',
    component: () => import('../views/tools/CommentGen.vue'),
    meta: { title: '评语生成', icon: '✍️' },
  },
  {
    path: 'toolbox/test-paper',
    name: 'tool-test-paper',
    component: () => import('../views/tools/TestPaper.vue'),
    meta: { title: '优选试卷', icon: '📝' },
  },
  {
    path: 'toolbox/lesson-plan',
    name: 'tool-lesson-plan',
    component: () => import('../views/tools/LessonPlan.vue'),
    meta: { title: '优质教案', icon: '📚' },
  },
  {
    path: 'toolbox/math',
    name: 'tool-math',
    component: () => import('../views/tools/MathGen.vue'),
    meta: { title: '口算生成', icon: '➕' },
  },
  {
    path: 'toolbox/vertical-calc',
    name: 'tool-vertical-calc',
    component: () => import('../views/tools/VerticalCalc.vue'),
    meta: { title: '竖式计算', icon: '📐' },
  },
  {
    path: 'toolbox/answer-card',
    name: 'tool-answer-card',
    component: () => import('../views/tools/AnswerCard.vue'),
    meta: { title: '口算答题卡', icon: '📋' },
  },
  {
    path: 'toolbox/multiplication-table',
    name: 'tool-multiplication-table',
    component: () => import('../views/tools/MultiplicationTable.vue'),
    meta: { title: '乘法口诀', icon: '🔢' },
  },
  {
    path: 'toolbox/unit-conversion',
    name: 'tool-unit-conversion',
    component: () => import('../views/tools/UnitConversion.vue'),
    meta: { title: '单位换算', icon: '⚖️' },
  },
  {
    path: 'toolbox/math-mistakes',
    name: 'tool-math-mistakes',
    component: () => import('../views/tools/MathMistakes.vue'),
    meta: { title: '错题本', icon: '📝' },
  },
  {
    path: 'toolbox/schedule-maker',
    name: 'tool-schedule',
    component: () => import('../views/tools/ScheduleMaker.vue'),
    meta: { title: '课表排版', icon: '🗓️' },
  },
  {
    path: 'toolbox/random-grouper',
    name: 'tool-grouper',
    component: () => import('../views/tools/RandomGrouper.vue'),
    meta: { title: '随机分组', icon: '👥' },
  },
  {
    path: 'toolbox/reward',
    name: 'tool-reward',
    component: () => import('../views/tools/Reward.vue'),
    meta: { title: '奖惩记录', icon: '🏅' },
  },
  {
    path: 'toolbox/class-duty',
    name: 'tool-class-duty',
    component: () => import('../views/tools/ClassDuty.vue'),
    meta: { title: '班级职务', icon: '🎖️' },
  },
  {
    path: 'toolbox/ai',
    name: 'tool-ai',
    component: () => import('../views/AI.vue'),
    meta: { title: 'AI 对话', icon: '🤖' },
  },
  {
    path: 'toolbox/translate',
    name: 'tool-translate',
    component: () => import('../views/tools/Translate.vue'),
    meta: { title: '翻译', icon: '🌐' },
  },
  {
    path: 'toolbox/flower',
    name: 'tool-flower',
    component: () => import('../views/tools/FlowerGame.vue'),
    meta: { title: '笑口常开', icon: '🌸' },
  },
  {
    path: 'toolbox/award',
    name: 'tool-award',
    component: () => import('../views/tools/AwardRecord.vue'),
    meta: { title: '我获奖啦', icon: '🏆' },
  },
  {
    path: 'toolbox/seat-map',
    name: 'tool-seat',
    component: () => import('../views/tools/SeatMap.vue'),
    meta: { title: '座位表', icon: '💺' },
  },
  {
    path: 'toolbox/score-panel',
    name: 'tool-score',
    component: () => import('../views/tools/ScorePanel.vue'),
    meta: { title: '加减分', icon: '🏅' },
  },
  {
    path: 'toolbox/notice-template',
    name: 'tool-notice-tpl',
    component: () => import('../views/tools/NoticeTemplate.vue'),
    meta: { title: '通知模板', icon: '📋' },
  },
  {
    path: 'toolbox/plan-template',
    name: 'tool-plan-tpl',
    component: () => import('../views/tools/PlanTemplateLib.vue'),
    meta: { title: '文案模板库', icon: '📑' },
  },
  {
    path: 'toolbox/paper',
    name: 'tool-paper',
    component: () => import('../views/tools/Paper.vue'),
    meta: { title: '教育论文', icon: '📝' },
  },
  {
    path: 'toolbox/knowledge',
    name: 'tool-knowledge',
    component: () => import('../views/tools/Knowledge.vue'),
    meta: { title: '知识点', icon: '💡' },
  },
  {
    path: 'toolbox/word-card',
    name: 'tool-word-card',
    component: () => import('../views/tools/WordCard.vue'),
    meta: { title: '英语单词卡片', icon: '📚' },
  },
  {
    path: 'toolbox/sentence-practice',
    name: 'tool-sentence-practice',
    component: () => import('../views/tools/SentencePractice.vue'),
    meta: { title: '英语句型练习', icon: '✨' },
  },
  {
    path: 'toolbox/stroke-order',
    name: 'tool-stroke-order',
    component: () => import('../views/tools/StrokeOrder.vue'),
    meta: { title: '汉字笔顺', icon: '✏️' },
  },
  {
    path: 'toolbox/writing-materials',
    name: 'tool-writing-materials',
    component: () => import('../views/tools/WritingMaterials.vue'),
    meta: { title: '作文素材', icon: '📖' },
  },
]
